Later improvements by jalsot
https://gist.github.com/jalsot/a24aa543021889ad0c70

diff --git a/qemu-debian-create-image b/qemu-debian-create-image
--- a/qemu-debian-create-image
+++ b/qemu-debian-create-image
@@ -1,10 +1,16 @@
 #!/bin/bash
 
-# Configs
-VSYSTEM=qemu					# Either 'qemu' or 'kvm'
-INCLUDES='less,vim,sudo,openssh-server,acpid'
-MIRROR="http://ftp.br.debian.org/debian"
-ARCH=686
+# Configs overwritable via environment variables
+VSYSTEM=${VSYSTEM:=qemu}					# Either 'qemu' or 'kvm'
+FLAVOUR=${FLAVOUR:=debian}					# Either 'debian' or 'ubuntu'
+INCLUDES=${INCLUDES:="less,vim,sudo,openssh-server,acpid"}
+MIRROR=${MIRROR:="http://ftp.hu.debian.org/debian"}
+#MIRROR=${MIRROR:="http://localhost:3142/debian"}
+#MIRROR=${MIRROR:="http://hu.archive.ubuntu.com/ubuntu/"}
+#MIRROR=${MIRROR:="http://localhost:3142/ubuntu"}
+ARCH=${ARCH:=amd64}
+APT_CACHER=${APT_CACHER:=no}
+IMGSIZE=${IMGSIZE:=8G}
 
 clean_debian() {
 	[ "$MNT_DIR" != "" ] && chroot $MNT_DIR umount /proc/ /sys/ /dev/ /boot/
@@ -48,6 +54,23 @@ MNT_DIR=`tempfile`
 rm $MNT_DIR
 mkdir $MNT_DIR
 DISK=
+
+# add apt cacher for faster rebuilds, runs on 3142
+if [ "$APT_CACHER" == "yes" ]; then
+    echo "Installing apt-cacher-ng for fast rebuilds"
+    apt-get install apt-cacher-ng
+fi
+
+if [ ! -f $FILE ]; then
+    echo "Creating $FILE"
+    $VSYSTEM-img create -f qcow2 $FILE $IMGSIZE
+fi
+
+if [ $FLAVOUR == "debian" ]; then
+    BOOT_PKG="linux-image-$ARCH grub-pc"
+elif [ $FLAVOUR == "ubuntu" ]; then
+    BOOT_PKG="linux-image-generic grub-pc"
+fi
 
 echo "Looking for nbd device..."
 
@@ -112,9 +135,10 @@ mount --bind /dev/ $MNT_DIR/dev || fail "cannot bind /dev"
 chroot $MNT_DIR mount -t ext4 ${DISK}p1 /boot || fail "cannot mount /boot"
 chroot $MNT_DIR mount -t proc none /proc || fail "cannot mount /proc"
 chroot $MNT_DIR mount -t sysfs none /sys || fail "cannot mount /sys"
-LANG=C DEBIAN_FRONTEND=noninteractive chroot $MNT_DIR apt-get install -y -q linux-image-$ARCH grub-pc || fail "cannot install linux-image and grub"
+LANG=C DEBIAN_FRONTEND=noninteractive chroot $MNT_DIR apt-get install -y --force-yes -q $BOOT_PKG || fail "cannot install $BOOT_PKG"
 chroot $MNT_DIR grub-install $DISK || fail "cannot install grub"
 chroot $MNT_DIR update-grub || fail "cannot update grub"
+chroot $MNT_DIR apt-get clean || fail "unable to clean apt cache"
 
 sed -i "s|${DISK}p1|/dev/vda1|g" $MNT_DIR/boot/grub/grub.cfg
 sed -i "s|${DISK}p2|/dev/vda2|g" $MNT_DIR/boot/grub/grub.cfg
